### ISSUE TITLE
error in csv for tunes

### ISSUE THREAD

**Issue by wolfchimneyrock** [adactio/TheSession-data#1]
It looks like you have a problem with linefeeds in the tunes data and missing linefeeds between rows, this is maybe caused by a bug in mac excel 2008 or 2011 ?

**Comment by adactio** [comment]
Hmmm …not sure. I've just pushed another dump of the data—let me know if the problem still persists.

**Comment by wolfchimneyrock** [comment]
running this _twice_ fixed it:
sed -i 's/\"/""/g' tunes.csv

the problem is:  you are using double quotes for the field delimeters, and the csv spec calls for double quotes in the data to be escaped with "" instead of \" which your data has, though i assume whatever tool you are using to export to csv thinks it is behaving properly but isn't

**Comment by adactio** [comment]
Ah, yes, that would be the database export tool I'm using. Hmm ...that's annoying.
