### ISSUE TITLE
"Recordings" contain unescaped quotes which breaks file imports

### ISSUE THREAD

**Issue by paniterka** [adactio/TheSession-data#11]
Hi, in both recordings.csv and recordings.json there are multiple entries with unescaped quotes in the tune name, see for example line 15564 in the csv:
`2823,BoneZone,"In Session",12,1,"Bonnie Ship "The Diamond", The",`
This breaks importing of both csv and json (I'm using python pandas). Could you please re-upload fixed files? thanks a lot!

**Comment by adactio** [comment]
Ah, good catch! I was eascaping the quotes in tune names but not track names on recordings.

I've re-exported the data now so you should be good to go!

Thanks for letting me know about this.

**Comment by paniterka** [comment]
Thanks a lot! It looks better now, but there is one more tricky entry (it turns out people can get really creative with names) - when you look for id 4490, they have yet another quote characters this time in the "recording" column: 
`4490,"The Glencraig Scottish Dance Band","The Reel Party: "Are Ye Askin'?"",1,3,"Magnister Voe",`
Similarly for id 5784 and 5246. Curiously, a similar entry with id 4085 gets parsed correctly. It would be really great if you could fix this one as well :)

**Comment by adactio** [comment]
Oops! Good catch! I've re-exported now so that should all be good. Thanks again!
