### ISSUE TITLE
Quotation marks in tune names causing malformed enries in aliases.json 

### ISSUE THREAD

**Issue by TomWyllie** [adactio/TheSession-data#12]
There appears to be a problem with quotation marks inside aliases of tune names. The following two tunes (and at this moment no other);

- [https://thesession.org/tunes/9275](https://thesession.org/tunes/9275)
- [https://thesession.org/tunes/18917](https://thesession.org/tunes/18917)

Have quotation marks in their aliased names, and in the `aliases.json` file generated from the database the entries are missing the `name` field;

- `{"tune_id":"9275","alias":"\"Come Into The Town, My Fair Lady\",\"Sean Dwyer's"},`
- `{"tune_id":"18917","alias":"\"When I Saw My Bonny Lass To The Church Go\",\"Men Of The Forest, The"},`

This is a minor issue and doesn't appear to have any effect on the website, it is probably limited to the script that generates these files from the database dump (which is excluded from this repository).

**Comment by adactio** [comment]
Oh, that's weird!

Short term, I'll fix those two aliases. Longer term, I'll take a look at the script to see if I can figure out what's happening.

**Comment by adactio** [comment]
I found the problem and pushed a fix. I've also re-exported the latest data.

Thanks for letting me know about this!
