### ISSUE TITLE
Vercel app JSON query returning empty record.

### ISSUE THREAD

**Issue by abalter** [adactio/TheSession-data#13]
This may not be the correct place to post this.

I navigated here:

https://thesession.vercel.app/thesession?sql=select+*+from+tunes+where+name+like+%22%25wise+maid%25%22%0D%0A

The query in the box shows

`select * from tunes where name like "%wise maid%"`

and the page displays results. If I click on the "This data as JSON" button, I get an empty record. This is the generated HTML REST query:

https://thesession.vercel.app/thesession.csv?sql=select%20*%20from%20tunes%20where%20name%20like%20%22%wise%20maid%%22&_size=max

I created a little app for myself a couple of months ago and it was working then, but stopped sometime in the last month.

Note: CSV queries also seem to come back empty.

https://thesession.vercel.app/thesession?sql=select+*+from+tunes+where+name+like+%22%25wise+maid%25%22

**Comment by adactio** [comment]
Hmm ...sorry about that! Sounds like it might be an issue with the `datasette` tool I'm using to generate that view of the data.

I've filed an issue over here:
https://github.com/simonw/datasette/issues/1437
