### ISSUE TITLE
In Sessions, a few with bad longitude/date

### ISSUE THREAD

**Issue by zmoon** [adactio/TheSession-data#15]
Loading from the JSON, three have date in the longitude, and then are missing a value for date.

![image](https://user-images.githubusercontent.com/15079414/196046270-b75a0fda-12b4-4b3a-9e4d-dac283c0badf.png)

ids [6878, 3789, 7291]

**Comment by adactio** [comment]
Ah, it looks like quotation marks in the name of the venue were throwing out the CSV columns. I've adjusted the names and re-exported so it should be all good now.

**Comment by zmoon** [comment]
Thanks!
