### ISSUE TITLE
Missing "L:"

### ISSUE THREAD

**Issue by boblsturm** [adactio/TheSession-data#2]
Hello adactio. I have a few questions.

1) Is this repo _all_ of the tunes and settings at The Session?
2) How come the "L:" field is missing?

Thanks!

**Comment by boblsturm** [comment]
It appears that L is always 1/8. :)

**Comment by boblsturm** [comment]
Other problems: 
I see some inconsistencies in the output, like:

14361,26313,"A L'envers","slip jig","9/8","Edorian","X: 1^M
T: A l'Envers^M
R: slip jig^M
M: 9/8^M
L: 1/8^M
E>F G>B A2|G>A B>G E>D|E>F G>B A2|1 G>A B>G E2:|2G>A B>G E>B||^M
c2A>c B>A|G>F E>F G>B|c2A>c B>A|1G>F G>B A>B:|2G>F G>B A2||^M
AA .e2 .A2 B2-|B>G A>B c>d c2 | A2 AA .e2 .A2 | B>G A>B c>d cB:||^M
","2015-04-15 19:26:06","Boris Rorsvort"

There are others. It appears to be in the ABC: https://thesession.org/tunes/7739. I count a few dozen.

**Comment by hillaryskye** [comment]
wow, i havent seen that altho i have seen that im usimg this api with abcjs
and the sheet music and it shows with noise on the header. i wonder if this
is related.

Hillary

**Comment by hillaryskye** [comment]
what field is the garbage coming from?

**Comment by boblsturm** [comment]
The "abc" field.

**Comment by hillaryskye** [comment]
can you show a few more examples of the abc fields with garbage

**Comment by boblsturm** [comment]
I just removed them! :) But see here: https://thesession.org/tunes/7739

**Comment by boblsturm** [comment]
If you dowload the tunes.csv and search for all occurances of "X:" you will find them. There are about 15 or so.

**Comment by hillaryskye** [comment]
I guess im not understanding what the 15 is to look for?
