### ISSUE TITLE
Data corruption?

### ISSUE THREAD

**Issue by douglaseck** [adactio/TheSession-data#4]
Hi, 
I noticed that the number of tunes in JSON with the abc field populated dropped a lot at some point. This might indicate some data corruption.  I haven't had time to zero in on when this happened. 

Old git repo I had from February:
~>grep \"abc\" old_tunes.json | wc -l 
**25207**
~>ls -l old_tunes.json 
-rw-r--r-- 1 deck eng 11293680 Feb 17 10:47 old_tunes.json

Current: 
~>grep \"abc\" new_tunes.json | wc -l
**4277**
~>ls -l new_tunes.json 
-rw-r--r-- 1 deck eng 11275523 Aug  3 15:27 new_tunes.json

Tailing each file suggests some problems in the new version:
~>tail new_tunes.json 
{"tune":"EAB cBA | FAB cBA | B2 B edc | B2 A-A F2 :|"},
{"tune":"|: d2 d-d2 c | d c2  B2 A | d2-d2 c d | B3 A3 |"},
{"tune":"2 d-d2 c | d c2  B2 A | d d-d2 c d | e3 e3 :|\",\"2010-04-27 09:29:02\",\"Barry Pearce\"\n10446,20379,\"Zycanthos\",\"jig\",\"6/8\",\"Aminor\",\"[M:5/8]|: a2 gag| e2a- ag| ec BcB| AF F2F|"},
{"tune":"EAB cB| FAB cB|B2 edB| cd cBA :|"},
{"tune":"|:EA cBA| FA cBA| B2 edB|Bcd BA|"},
{"tune":"EA cBA| FA cBA| B2 edB|1 B2 A2 F :|2 B2 A2 B |"},
{"tune":"|: d2 d2 c | dcd BA | d3/2 d3/2 cd | BcB BA |"},
{"tune":"2 d2 c | dcd B A| d3/2 d3/2 cd | e2 ecA :|\",\"2010-04-28 03:47:13\",\"Tøm\"\n6040,6040,\"Ølland\",\"waltz\",\"3/4\",\"Gmajor\",\"AB |: c2 cd cB | A2 AB cd | e2 g2 f2 |1 e4 AB :|2 e4 e2||"},
{"tune":"|: e2> c2 c2 |c2 ec eg | f2 d2 d2 | d2 d^c df |"}

~>tail old_tunes.json
{"tune":3731,"setting":21666,"name":"Zoe's","type":"waltz","meter":"3/4","mode":"Gmajor","abc":"|:D2|B3 A BA|G2 D2 D2|E3 F GE|D4 D2|\r\nB3 A Bc|d3 ^c de|d2 B2 G2|A4 D2|\r\nB3 A BA|G2 D2 D2|E3 F GA|B4 BA|\r\nG3 A BG|E3 F GE|D G3 F2|G4:|\r\n|:d2|g3 a bg|a f3 a2|g e3 g2|d4 d2|\r\ne3 f ge|d2 g2 a2|b3 a g2|a4 d2|\r\ng3 a bg|a f3 a2|g e3 g2|d3 c BA|\r\nG3 A BG|E3 F GE|D G3 F2|G4:|","date":"2013-06-08 08:56:10","username":"Tøm"},
{"tune":11995,"setting":11995,"name":"Zoidberg's","type":"jig","meter":"6/8","mode":"Dmajor","abc":"|:f2f f2a | fed B2A | A2A ABd | e2e ~e2e |\r\nf2f f2a | fed B2A | B2d A2d | Adc d3 :|\r\n|: a2a afd | b2b bgd | a2a afd | efe B2A |\r\n[1 a2a afd | b2b bgd | a2a afd | efe ede :|\r\n[2 B2d A2d | B2d A2d | B2d A2d | Adc d3 ||","date":"2012-06-19 12:12:46","username":"DrugCrazed"},
{"tune":11584,"setting":11584,"name":"Zonaradikos","type":"jig","meter":"6/8","mode":"Dmajor","abc":"A|:d3 e3|f3-f2e|fga gfe|d2c B2A|\r\nd3 e3|f3-f2e|fga gfe|d2c B2A|\r\nd3 e3|f3-f2e|fga gfe|d2c B3|\r\ne2e gfe|d2c B2A|Bcd efg|B3 B3:|\r\ne2e gfe|d2c B3|e2e gfe|d2c B3|\r\ne2e gfe|d2c B2A|Bcd efg|B6:|\r\nfga gfe|f2B f2B|fga gfe|d2c B3|\r\nfga gfe|f2B f2B|fga gfe|d2c B3|\r\nfga gfe|f2B f2B|fga gfe|d2c B3|\r\ne2e gfe|d2c B2A|Bcd efg|B6:|\r\ne2d cBA|Bcd e2A|e2d cBA|B2e B3|\r\ne2d cBA|Bcd e2A|e2d cBA|B3 Bcd|\r\ne2d cBA|Bcd e2A|e2d cBA|B2e B3|\r\ne2d cBA|Bcd e2A|e2d cBA|B3 B3|","date":"2011-11-14 16:06:26","username":"gian marco"},
{"tune":9013,"setting":9013,"name":"Zucchini Reel, The","type":"reel","meter":"4/4","mode":"Dmajor","abc":"Ac|d2d=c ADFA|G2BG =cGBG|Add=c ADFD|GBAG FDAc|\r\nd2d=c ADFA|G2BG =cGBG|Add=c ADFD|GBAG FDAd|\r\neffd gfed|cABc  d2 de|f2fd gfed|eaag e2 de|\r\neffd gfed| cABc  d2 A=c|d2d=c ADFD| GBAG FDD2|","date":"2008-10-18 06:05:43","username":"banjobabe"},
{"tune":13875,"setting":24924,"name":"Zuppa Inglese","type":"jig","meter":"6/8","mode":"Gmajor","abc":"GAG GAB| cBc cde| d2B GAB| A2G E2D|\r\nGAG GAB| cBc cde| d2B GAB| A2A A3:|\r\ngdB fdA| ecG dBG| cAF BGD| DFA GBd|\r\ngdB fdA| ecG dBG| cAF BGD| DFA G3:|\r\nA3 B3| c3 ^c3|[fd][fd][fd] [g2d2][fd]| [g2d2][fd] z3|\r\nA3 B3| c3 ^c3|d2A F2A| D3 z3|\r\nA3 B3| c3 ^c3|[fd][fd][fd] [g2d2][fd]| [g2d2][fd] z3|\r\nA3 B3| [cG][cG][cG] [cG][cG][cG]|[cG][cG][cG] [cG][cG][cG]|[c2G2]z z3|","date":"2014-10-07 22:55:26","username":"Edward Nunn"},
{"tune":10446,"setting":10446,"name":"Zycanthos","type":"jig","meter":"6/8","mode":"Aminor","abc":"|: a2 a gag | e2 a a2 g | ecc BcB | AFF F3 |\r\nEAB cBA | FAB cBA | B2 B edc| Bcd cBA :|\r\n|: EAB cBA | FAB cBA | B2 B edc | Bcd cBA |\r\nEAB cBA | FAB cBA | B2 B edc | B2 A-A F2 :|\r\n|: d2 d-d2 c | d c2  B2 A | d2-d2 c d | B3 A3 |\r\nd2 d-d2 c | d c2  B2 A | d d-d2 c d | e3 e3 :|","date":"2010-04-27 09:29:02","username":"Barry Pearce"},
{"tune":10446,"setting":20379,"name":"Zycanthos","type":"jig","meter":"6/8","mode":"Aminor","abc":"[M:5/8]|: a2 gag| e2a- ag| ec BcB| AF F2F|\r\nEAB cB| FAB cB|B2 edB| cd cBA :|\r\n|:EA cBA| FA cBA| B2 edB|Bcd BA|\r\nEA cBA| FA cBA| B2 edB|1 B2 A2 F :|2 B2 A2 B |\r\n|: d2 d2 c | dcd BA | d3/2 d3/2 cd | BcB BA |\r\nd2 d2 c | dcd B A| d3/2 d3/2 cd | e2 ecA :|","date":"2010-04-28 03:47:13","username":"Tøm"},
{"tune":6040,"setting":6040,"name":"Ølland","type":"waltz","meter":"3/4","mode":"Gmajor","abc":"AB |: c2 cd cB | A2 AB cd | e2 g2 f2 |1 e4 AB :|2 e4 e2||\r\n|: e2> c2 c2 |c2 ec eg | f2 d2 d2 | d2 d^c df |\r\ne3 dcB |A2>B2 c2 | B2 G2 G2 |A6 :|","date":"2006-07-28 15:19:26","username":"Kuddel"},
{"tune":6040,"setting":17944,"name":"Ølland","type":"waltz","meter":"3/4","mode":"Ddorian","abc":"F2 FG FE | D2 DE FG | A2 c2- cB | A4- :|\rA2 FA FA | F2 AF Ac | B2 GB GB | G2 BG (3Bcd |\rA2- AG FE | DE- E2 F2 | E2 C2- CC | D4 :|","date":"2006-07-30 13:32:55","username":"ceolachan"}

**Comment by adactio** [comment]
Thanks for alerting me to this. I suspect the data corruption is happening when the conversion from CSV to JSON happens (I export as CSV, and then run a command line tool to make the JSON files from the CSV files).

Digging into the JSON file, it looks like the corruption happens right around the tune "The Arrival Of The Queen Of Sheba", which is very complex with lots of slashes and quotes flying around—exactly the kind of thing that would mess up a JSON parser. I've edited that setting and re-exported the CSV, and recreated the JSON, so here's hoping that things are back on track.

Thanks again for bringing this to my attention: I haven't been checking the CSV to JSON conversion for errors.
