### ISSUE TITLE
Quotes have extra escaped-backslash in json

### ISSUE THREAD

**Issue by campagnola** [adactio/TheSession-data#5]
The problem can be seen in the fifth entry in `tunes.json`, id=13684.
The json fetched from thesession.org begins like (https://thesession.org/tunes/13684?format=json):
    
    "abc": "[|: &quot;A&quot;.d.DD/D/D

In the CSV file it looks correct with escaped quotes:

    "[|: \"A\".d.DD/D/D

But in the JSON file, the backslash is escaped again, giving:

    "abc":"[|: \\\"A\\\".d.DD/D/D

This renders the tune unparseable..

**Comment by adactio** [comment]
Thanks for bringing this to my attention.

I'm using a command-line tool called csvtojson to the converting, and it looks like I need to explicitly state what character is being used for escaping (I'm putting this here for future me to find):

`csvtojson --escape='\' csv/tunes.csv > json/tunes.json`

The latest data dump should have correctly formatted JSON.
