### ISSUE TITLE
Cant parse the json file in python due to encoding issues. 

### ISSUE THREAD

**Issue by Ddedalous** [adactio/TheSession-data#7]
Hi can you tell me the encoding for the tunes.json file. because its not parsing for me . thanks a million in advance....

**Comment by adactio** [comment]
I'm using this tool to convert the CSV files (which are exported directly from the database) into JSON:

https://www.npmjs.com/package/csvtojson
https://github.com/Keyang/node-csvtojson

I can't find any information about encoding in the docs there. What's the specific encoding issue being thrown up?
