### ISSUE TITLE
Inconsistent aliases.json entries

### ISSUE THREAD

**Issue by mccannjb** [adactio/TheSession-data#8]
There are two issues with the JSON version of the aliases table.

[line 18873]: There is no "name" field provided on this entry
> {"tune_id":"7367","alias":"Fighting \\\"59th\\\",\"Fighting 59th, The"},

[line 25382]: This entry has an additional field ["field4"] that appears to be from a parsing issue (the 'name' field also seems to be incorrect)
> {"tune_id":"16882","alias":"Canadian Waltz (Boys Of The Lough, \\\"Good Friends-Good Music\\","name":"1977)\"","field4":"Barry's Bay"},

**Comment by adactio** [comment]
Thanks for the heads-up: looks like both issues were being caused by quotemarks in the aliases. I've fixed both of them and re-exported the files.
