### ISSUE TITLE
CSV uses incorrect quote escaping

### ISSUE THREAD

**Issue by dracos** [adactio/TheSession-data#9]
It's using backslash instead of another quote (RFC4180). I see https://github.com/adactio/TheSession-data/issues/1 was closed, but it's still present - what database tool is being used to export? mysql/postgresql both let you specify the escape character in an export, happy to help work out what needs changing.

**Comment by adactio** [comment]
I'm using Sequel Pro to export the CSV files (from The Session's MySQL database).

Maybe I should file a bug over there?
https://github.com/sequelpro/sequelpro/issues

**Comment by dracos** [comment]
<img src="https://cloud.githubusercontent.com/assets/266088/15770205/0c4a322a-29a5-11e6-9ceb-bf0ce28e764b.png">

I think there's a place in the app you can set the escape character? If you can find that, and set it to the double quote character, I think that should hopefully create compliant Excel/datasette compatible CSV output.

**Comment by adactio** [comment]
But if you run a query in Sequel Pro and then want to export the results of that query as CSV, there are no options available.

(That's how the data here in this repo is generated: running queries that join tables together)

**Comment by dracos** [comment]
The screenshot in the (unrelated) bug report at https://github.com/sequelpro/sequelpro/issues/3254 seems to show the export result as CSV window does include the relevant options? Sorry, I'm not on a Mac or I'd look myself.

**Comment by adactio** [comment]
No, that screenshot is from a regular export—there's a different mechanism for exporting the results of running a query as CSV.

**Comment by adactio** [comment]
Ah, got it! Not sure how I missed that.

I've re-exported the CSV files now with the right escaping. I'll try to remember to check that in future.

Thanks for the help, Matthew—much appreciated!
